name: Автообновление прогноза

on:
  schedule:
    - cron: '0 6 * * *'   # 09:00 по МСК (UTC+3)
    - cron: '0 18 * * *'  # 21:00 по МСК
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: 📥 Клонирование репозитория
        uses: actions/checkout@v3

      - name: 🐍 Установка Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: 📦 Установка зависимостей
        run: pip install gtts

      - name: ⚙ Генерация прогнозов
        run: |
          python generate_predictions.py
          python generate_mp3.py

      - name: 💾 Коммит и пуш изменений
        run: |
          git config user.name "GitHub Actions"
          git config user.email "actions@github.com"
          git add predictions.json prediction.mp3
          git commit -m "🔄 Автообновление прогноза"
          git push
